In [1]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing() 

In [2]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # display multiple results

In [4]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="gotham" color="purple"> Operaciones matriciales</font>

Las operaciones de _suma_ de matrices son sencillas:
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$, where ${0}$ is the zero matrix
7. For any $A$, there exists an $- A$, such that $ A+(- A)=0$.

Son tan obvios como parece, por lo que no se aportan pruebas. Y las propiedades de la _multiplicación_ de la matriz son:
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$

Tenga en cuenta que debemos diferenciar dos tipos de multiplicación, **multiplicación de Hadamard** (multiplicación por elementos) y **multiplicación de matrices**:

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [6]:
A*B # this is Hadamard elementwise product

array([[ 5, 12],
       [21, 32]])

In [7]:
A@B # this is matrix product

array([[19, 22],
       [43, 50]])

We show explicitly the matrix multiplication rule:

In [8]:
np.sum(A[0,:]*B[:,0]) # (1, 1)
np.sum(A[1,:]*B[:,0]) # (2, 1)
np.sum(A[0,:]*B[:,1]) # (1, 2)
np.sum(A[1,:]*B[:,1]) # (2, 2)

19

43

22

50

## <font face="gotham" color="purple"> Demostración de SymPy: suma</font>

Definamos todas las letras como símbolos en caso de que podamos usarlas repetidamente.

In [9]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [10]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [11]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

## <font face="gotham" color="purple"> Demostración de SymPy: multiplicación </font>

Las reglas de multiplicación de matrices se pueden entender claramente mediante el uso de símbolos.

In [12]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [13]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

## <font face="gotham" color="purple"> Conmutabilidad </font>

La multiplicación de matrices generalmente no conmuta, de modo que ${AB} \neq {BA}$. Por ejemplo, considere $ A$ y $ B$:

In [14]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B
B*A

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

⎡36  44⎤
⎢      ⎥
⎣13  16⎦

¿Cómo encontramos una matriz conmutable?

In [15]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

Para mostrar ${AB} = {BA}$, necesitamos probar ${AB} - {BA} = 0$

In [16]:
M = A*B - B*A; M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

Eso significa

\begin{align}
b g - c f&=0 \\
 a f - b e + b h - d f&=0\\
- a g + c e - c h + d g&=0 \\
- b g + c f&=0
\end{align}

Si tratamos $a, b, c, d$ como coeficientes del sistema, extraemos una matriz aumentada

In [17]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d -a, -c], [0, c, -b, 0]]); A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

Realice la eliminación **Gauss-Jordan** hasta que la fila se reduzca.

In [18]:
A_aug.rref()

⎛⎡        a   d    ⎤        ⎞
⎜⎢1  0  - ─ + ─  -1⎥        ⎟
⎜⎢        c   c    ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢        -b       ⎥        ⎟
⎜⎢0  1    ───    0 ⎥, (0, 1)⎟
⎜⎢         c       ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢0  0     0     0 ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎝⎣0  0     0     0 ⎦        ⎠

La solución general es
\begin{align}
e - \frac{a-d}cg - h &=0\\
f - \frac{b}{c} & =0\\
g &= free\\
h & =free
\end{align}

si establecemos coeficientes $a = 10, b = 12, c = 20, d = 8$, o $ A = \left[\begin{matrix}10 & 12\\20 & 8\end{matrix}\right]$ entonces la solución general se convierte en


\begin{align}
e - .1g - h &=0\\
f - .6 & =0\\
g &= free\\
h & =free
\end{align}
Luego prueba una solución especial cuando $g = h = 1$
\begin{align}
e  &=1.1\\
f & =.6\\
g &=1 \\
h & =1
\end{align}
Y esta es una **matriz conmutable de $A$**, la denotamos $ C$.

In [19]:
C = sy.Matrix([[1.1, .6], [1, 1]]);C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

Ahora podemos ver que ${AC}={CA}$.

In [20]:
A = sy.Matrix([[10, 12], [20, 8]])
A*C
C*A

⎡23.0  18.0⎤
⎢          ⎥
⎣30.0  20.0⎦

⎡23.0  18.0⎤
⎢          ⎥
⎣ 30    20 ⎦

# <font face="gotham" color="purple"> Transposición de matrices</font>

Matriz $A_{n\times m}$ y su transpuesta es

In [21]:
A = np.array([[1, 2, 3], [4, 5, 6]]); A
A.T # transpose

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A
A.transpose()

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

Las propiedades de la transposición son
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

Podemos mostrar por qué la última propiedad se cumple con SymPy, definir $A$ y $B$, multiplicarlos y luego transponerlos, eso significa $(AB)^T$

In [23]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_tr = AB.transpose(); AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Transponga cada uno de ellos, luego multiplíquelo, eso significa $B^TA^T$

In [24]:
B_tr_A_tr = B.transpose()*A.transpose()
B_tr_A_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

Para ver si son iguales

In [25]:
AB_tr - B_tr_A_tr

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

# <font face="gotham" color="purple"> Matrices de identidad</font>

Esta es una matriz de identidad $I_5$

In [26]:
sy.eye(5)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

Propiedades de la matriz de identidad:

$$
AI=IA = A
$$

Generemos $ I$ y $ A$ y mostremos si se cumple

In [27]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
A = np.around(np.random.rand(5, 5)*100); A # generar una matriz aleatoria

array([[59., 75., 69., 73., 34.],
       [94.,  8., 73.,  6., 10.],
       [73., 23., 55., 27., 67.],
       [ 1., 36., 25., 68., 75.],
       [35., 10., 33., 31., 79.]])

Aparentemente se mantiene

In [29]:
A@I - I@A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# <font face="gotham" color="purple"> Matriz elemental</font>

Una **matriz elemental** es una matriz que se puede obtener a partir de una operación de fila elemental única en una matriz identidad. Como:

$$
\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr 0 & 0 & 1\end{matrix}\right]\ \matrix{R_1\leftrightarrow R_2\cr ~\cr ~}\qquad\Longrightarrow\qquad \left[\begin{matrix}0 & 1 & 0\cr 1 & 0 & 0\cr 0 & 0 & 1\end{matrix}\right]
$$

donde $R_1\leftrightarrow R_2$ significa intercambiar la fila $1$ y la fila $2$, y denotamos la matriz transformada como ${E}$, luego multiplicamos $ E$ por la izquierda en una matriz $ A$. Genera $ A$ primero

In [30]:
A = sy.randMatrix(3, percent = 80); A # generate a random matrix with 80% of entries being nonzero

⎡34  5   0 ⎤
⎢          ⎥
⎢34  67  4 ⎥
⎢          ⎥
⎣14  32  44⎦

Crea una matriz elemental con $R_1\leftrightarrow R_2$

In [31]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

Resulta que al multiplicar $ E$ por la izquierda por $ AN$, $ A$ también cambia la fila $1$ y $2$.

In [32]:
E*A

⎡34  67  4 ⎤
⎢          ⎥
⎢34  5   0 ⎥
⎢          ⎥
⎣14  32  44⎦

Sumar un múltiplo de una fila a otra fila en la matriz identidad también nos da una matriz elemental.

$$
\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr 0 & 0 & 1\end{matrix}\right]\ \matrix{~\cr ~\cr R_3-7R_1}\qquad\longrightarrow\left[\begin{matrix}1 & 0 & 0\cr 0 & 1 & 0\cr -7 & 0 & 1\end{matrix}\right]
$$

Verifiquemos con SymPy.

In [33]:
A = sy.randMatrix(3, percent = 80); A
E = sy.Matrix([[1, 0, 0], [0, 1, 0], [-7, 0, 1]]); E

⎡72  31  34⎤
⎢          ⎥
⎢25  12  7 ⎥
⎢          ⎥
⎣54  8   0 ⎦

⎡1   0  0⎤
⎢        ⎥
⎢0   1  0⎥
⎢        ⎥
⎣-7  0  1⎦

In [34]:
E*A

⎡ 72    31    34 ⎤
⎢                ⎥
⎢ 25    12    7  ⎥
⎢                ⎥
⎣-450  -209  -238⎦

También podemos mostrar esto mediante una operación de fila explícita en $ A$.

In [35]:
EA = sy.matrices.MatrixBase.copy(A)
EA[2,:]=-7*EA[0,:]+EA[2,:]
EA

⎡ 72    31    34 ⎤
⎢                ⎥
⎢ 25    12    7  ⎥
⎢                ⎥
⎣-450  -209  -238⎦

En la siguiente sección, veremos una conclusión importante de la multiplicación de matrices elementales: una **matriz invertible** es un producto de una serie de matrices elementales.

# <font face="gotham" color="purple"> Matrices inversas </font>

Si ${AB}={BA}=\mathbf{I}$, $ B$ se llama inversa de la matriz $ A$, denotada como $ B= A^{-1}$.


NumPy tiene una función conveniente ```np.linalg.inv()``` para calcular matrices inversas. Generar $A$

In [36]:
A = np.round(10*np.random.randn(5,5)); A

array([[ -1.,  -8.,  -6.,  -2., -16.],
       [ -1.,  -2.,   8., -13.,   4.],
       [  1.,  11., -13.,   2.,   3.],
       [ -1., -13.,   6.,   8.,   9.],
       [-12.,   9.,  -4.,  -1.,   7.]])

In [37]:
Ainv = np.linalg.inv(A); Ainv

array([[-0.026,  0.013,  0.042, -0.005, -0.078],
       [-0.048, -0.038, -0.034, -0.064,  0.01 ],
       [-0.05 , -0.034, -0.096, -0.043,  0.003],
       [-0.026, -0.08 , -0.04 , -0.002,  0.006],
       [-0.015,  0.041,  0.055,  0.049, -0.002]])

Verify if they are truly inverse of each other

In [38]:
A@Ainv

array([[ 1.,  0., -0.,  0., -0.],
       [-0.,  1.,  0., -0.,  0.],
       [-0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -0.],
       [ 0., -0., -0.,  0.,  1.]])

```-0.``` significa que hay más dígitos después del punto, pero se omite aquí.

## <font face="gotham" color="purple"> $[A\,|\,I]\sim{[I\,|\,A^{-1}]} Algoritmo </font>

Una forma conveniente de calcular la inversa es que podemos construir una matriz aumentada $[ A\,|\,\mathbf{I}]$, luego multiplicar una serie de $ E$ que son operaciones de fila elementales hasta la matriz $A$ se convierte en forma reducida de fila, si es de rango completo significa $ A \rightarrow \mathbf{I}$. Entonces $\mathbf{I}$ en el lado derecho de la matriz aumentada se convertirá en $ A^{-1}$ automáticamente.

Podemos mostrar con la función ```.rref()``` de SymPy en la matriz aumentada $[A\,|\,I]$.

In [39]:
AI = np.hstack((A, I)) # stack the matrix A and I horizontally
AI = sy.Matrix(AI); AI

⎡-1.0   -8.0   -6.0   -2.0   -16.0  1.0  0.0  0.0  0.0  0.0⎤
⎢                                                          ⎥
⎢-1.0   -2.0    8.0   -13.0   4.0   0.0  1.0  0.0  0.0  0.0⎥
⎢                                                          ⎥
⎢ 1.0   11.0   -13.0   2.0    3.0   0.0  0.0  1.0  0.0  0.0⎥
⎢                                                          ⎥
⎢-1.0   -13.0   6.0    8.0    9.0   0.0  0.0  0.0  1.0  0.0⎥
⎢                                                          ⎥
⎣-12.0   9.0   -4.0   -1.0    7.0   0.0  0.0  0.0  0.0  1.0⎦

In [40]:
AI_rref = AI.rref(); AI_rref

⎛⎡1  0  0  0  0  -0.0257937689879073  0.0134627985941502   0.0420563531303985 
⎜⎢                                                                            
⎜⎢0  1  0  0  0  -0.0475017432957576  -0.0379022282648688  -0.0338111774166985
⎜⎢                                                                            
⎜⎢0  0  1  0  0  -0.0496953174550335  -0.0339723665721724  -0.0957148213428458
⎜⎢                                                                            
⎜⎢0  0  0  1  0  -0.0259829910399854  -0.0804474050298025  -0.0399608941092372
⎜⎢                                                                            
⎝⎣0  0  0  0  1  -0.0152533998647413   0.04090525231359    0.0551652364049212 

  -0.00488473223327575  -0.0783939953535474 ⎤                 ⎞
                                            ⎥                 ⎟
  -0.0638116329512683   0.00961703559126635 ⎥                 ⎟
                                            ⎥                 ⎟
  -0.0433738992707943   0.002610

Extraiga el bloque RHS, este es $A^{-1}$.

In [41]:
Ainv = AI_rref[0][:,5:];Ainv # extract the RHS block

⎡-0.0257937689879073  0.0134627985941502   0.0420563531303985   -0.00488473223
⎢                                                                             
⎢-0.0475017432957576  -0.0379022282648688  -0.0338111774166985  -0.06381163295
⎢                                                                             
⎢-0.0496953174550335  -0.0339723665721724  -0.0957148213428458  -0.04337389927
⎢                                                                             
⎢-0.0259829910399854  -0.0804474050298025  -0.0399608941092372  -0.00152428875
⎢                                                                             
⎣-0.0152533998647413   0.04090525231359    0.0551652364049212    0.04866686056

327575  -0.0783939953535474 ⎤
                            ⎥
12683   0.00961703559126635 ⎥
                            ⎥
07943   0.00261056349626286 ⎥
                            ⎥
285147  0.00566614922611685 ⎥
                            ⎥
08682   -0.00159612305039964⎦

Escribí una función para redondear los números flotantes a los dígitos $4$, en la parte superior de este archivo, pero esto no es absolutamente necesario.

In [42]:
round_expr(Ainv, 4) 

⎡-0.0258  0.0135   0.0421   -0.0049  -0.0784⎤
⎢                                           ⎥
⎢-0.0475  -0.0379  -0.0338  -0.0638  0.0096 ⎥
⎢                                           ⎥
⎢-0.0497  -0.034   -0.0957  -0.0434  0.0026 ⎥
⎢                                           ⎥
⎢-0.026   -0.0804   -0.04   -0.0015  0.0057 ⎥
⎢                                           ⎥
⎣-0.0153  0.0409   0.0552   0.0487   -0.0016⎦

Podemos verificar si $AA^{-1}=\mathbf{I}$

In [43]:
A = sy.Matrix(A)
round_expr(A*Ainv, 4) 

⎡1.0   0    0    0   0.0⎤
⎢                       ⎥
⎢0.0  1.0  0.0   0   0.0⎥
⎢                       ⎥
⎢0.0  0.0  1.0  0.0  0.0⎥
⎢                       ⎥
⎢0.0  0.0  0.0  1.0  0.0⎥
⎢                       ⎥
⎣0.0   0    0   0.0  1.0⎦

Obtuvimos $\mathbf{I}$, lo que significa que el bloque RHS es de hecho $A^{-1}$.

## <font face="gotham" color="purple"> Un ejemplo de existencia de inversa </font>

Determine los valores de $\lambda$ tales que la matriz
$$A=\left[ \begin{matrix}3 &\lambda &1\cr 2 & -1 & 6\cr 1 & 9 & 4\end{matrix}\right]$$
no es reversible.

Aún así, estamos usando SymPy para resolver el problema.

In [44]:
lamb = sy.symbols('lamda') # SymPy will automatically render into LaTeX greek letters
A = np.array([[3, lamb, 1], [2, -1, 6], [1, 9, 4]])
I = np.eye(3); A

array([[3, lamda, 1],
       [2, -1, 6],
       [1, 9, 4]], dtype=object)

Forme la matriz aumentada.

In [45]:
AI = np.hstack((A, I))
AI = sy.Matrix(AI); AI

⎡3  λ   1  1.0  0.0  0.0⎤
⎢                       ⎥
⎢2  -1  6  0.0  1.0  0.0⎥
⎢                       ⎥
⎣1  9   4  0.0  0.0  1.0⎦

In [46]:
AI_rref = AI.rref()
AI_rref

⎛⎡             116.0       8.0⋅λ - 18.0  -12.0⋅λ - 2.0⎤           ⎞
⎜⎢1  0  0  ─────────────  ─────────────  ─────────────⎥           ⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢              4.0           -22.0           32.0    ⎥           ⎟
⎜⎢0  1  0  ─────────────  ─────────────  ─────────────⎥, (0, 1, 2)⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢             57.0          27.0 - λ     2.0⋅λ + 3.0 ⎥           ⎟
⎜⎢0  0  1   ──────────    ─────────────  ─────────────⎥           ⎟
⎝⎣          -6⋅λ - 465    2.0⋅λ + 155.0  2.0⋅λ + 155.0⎦           ⎠

Para hacer invertible la matriz $A$ notamos que es una de las condiciones a cumplir (en los denominadores):
\begin{align}
-6\lambda -465 &\neq0\\
\end{align}

Resuelviendo para $\lambda$.

In [47]:
sy.solvers.solve(-6*lamb-465, lamb)

Entonces este es uno de los $\lambda$ que hacen que la matriz sea invertible. Probemos con **determinante**. Si $| A|=0$, entonces la matriz no es invertible. No te preocupes por los determinantes, volveremos a esto.

In [48]:
A = np.array([[3, -155/2, 1], [2, -1, 6], [1, 9, 4]])
np.linalg.det(A)

El $| A|$ es $0$.

Entonces encontramos que una condición, siempre que $\lambda \neq -\frac{155}{2}$, la matriz $A$ sea invertible.

## <font face="gotham" color="purple"> Propiedades de las matrices inversas </font>

1. Si $A$ y $B$ son ambos invertibles, entonces $(AB)^{-1}=B^{-1}A^{-1}$.
2. Si $A$ es invertible, entonces $(A^T)^{-1}=(A^{-1})^T$.
3. Si $A$ y $B$ son ambos invertibles y simétricos, de modo que $AB=BA$, entonces $A^{-1}B$ es simétrico.

La _primera propiedad_ es sencilla
\begin{align}
ABB^{-1}A^{-1}=AIA^{-1}=I=AB(AB)^{-1}
\end{align}

El truco de la segunda propiedad es demostrar que
$$
A^T(A^{-1})^T = I
$$
Podemos usar la propiedad de transponer.
$$
A^T(A^{-1})^T=(A^{-1}A)^T = I^T = I
$$

La tercera propiedad es mostrar
$$
A^{-1}B = (A^{-1}B)^T
$$
Nuevamente use la propiedad de transponer.
$$
(A^{-1}B)^{T}=B^T(A^{-1})^T=B(A^T)^{-1}=BA^{-1}
$$
Usamos la condición $AB = BA$ para proceder
\begin{align}
AB&=BA\\
A^{-1}ABA^{-1}&=A^{-1}BAA^{-1}\\
BA^{-1}&=A^{-1}B
\end{align}
El complemento en la ecuación anterior, tenemos
$$
(A^{-1}B)^{T}=BA^{-1}=A^{-1}B
$$